-- Generated by the EN engine fork. Every workspace (and the cabinet "my") is one table of
-- (id, t, up, ord, val) rows inside a single MySQL database. Safe to re-run: CREATE IF NOT EXISTS
-- and INSERT IGNORE never touch existing rows.
SET NAMES utf8mb4;

-- Personal cabinet: users, their workspaces, roles, cabinet reports
CREATE TABLE IF NOT EXISTS `my` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `t` int unsigned NOT NULL,
  `up` int unsigned NOT NULL,
  `ord` int unsigned NOT NULL,
  `val` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `up_t` (`up`,`t`),
  KEY `t_val` (`t`,`val`(127))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Template cloned into every new workspace (newDb(): CREATE TABLE <ws> LIKE en; INSERT ... SELECT)
CREATE TABLE IF NOT EXISTS `en` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `t` int unsigned NOT NULL,
  `up` int unsigned NOT NULL,
  `ord` int unsigned NOT NULL,
  `val` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `up_t` (`up`,`t`),
  KEY `t_val` (`t`,`val`(127))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
